### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Hax0rG1rl** [hakluke/hakscale#1]
Hi,

Thanks for this, looks neat. I am trying to use it with nuclei + some custom templates. 

I have modified the initial container to install nuclei successfully. Then I tried a dry run with something like this: 

```hakscale push -p "host:./scope.txt" -c "nuclei -u _host_" -t 20 -q dryRun```

As a result, I get "exit status 127".

So, two things here: 

1. Would be too much to ask if you, could document, say, top 5 error messages someone might get while trying to use this tool? This way that someone can understand what he eventually did wrong in the process. :)   

2. Furthermore, is there anything wrong in my command syntax? 

Thanks!

**Comment by hakluke** [comment]
Hey! The command looks fine, and "exit status 127" looks like something stemming from the OS. I think it's likely that you ran out of memory while it was running.

How much RAM does the instance have?
